analyzer_rules:
  - explicit_self

disabled_rules:
  - trailing_whitespace
  - private_outlet

excluded:
  - Pods

file_length:
  - 500
  - 1200

force_cast: warning

force_try: warning

included:
  - CurrencyExchanger

custom_rules:
  already_true:
    regex: "== true"
    message: "Don't compare to true, just use the bool value."
  already_bool:
    regex: "== false"
    message: "Don't compare to false, just use !value."

opt_in_rules:
  - anyobject_protocol
  - closure_spacing
  - collection_alignment
  - convenience_type
  - empty_count
  - empty_xctest_method
  - explicit_init
  - fatal_error_message
  - first_where
  - function_default_parameter_at_end
  - identical_operands
  - implicit_return
  - joined_default_parameter
  - last_where
  - legacy_random
  - let_var_whitespace
  - modifier_order
  - multiline_arguments
  - multiline_parameters
  - operator_usage_whitespace
  - overridden_super_call
  - private_outlet
  - prohibited_super_call
  - redundant_nil_coalescing
  - static_operator
  - toggle_bool
  - unavailable_function
  - unneeded_parentheses_in_closure_argument
  - untyped_error_in_catch
  - unused_control_flow_label
  - vertical_parameter_alignment_on_call
  - xct_specific_matcher

  # Experimental
  - unused_import

reporter: xcode

type_body_length:
  - 300
  - 400
