# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CommissionCalculator' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CommissionCalculator

  target 'CommissionCalculatorTests' do
    # Pods for testing
  end

end

target 'CurrencyExchanger' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CurrencyExchanger
  pod 'IQKeyboardManagerSwift'

  target 'CurrencyExchangerTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'CurrencyExchangerUITests' do
    # Pods for testing
  end

end
