# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CurrencyExchanger' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'IQKeyboardManagerSwift'
  pod 'SwiftLint'

  target 'CurrencyExchangerTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'CurrencyExchangerUITests' do
    # Pods for testing
  end

end
